language: ruby
bundler_args: --without production

rvm:
  - 2.1.3

script:
  - RAILS_ENV=test bundle exec rspec spec

notifications:
  email:
    recipients:
      - thucquyendn@gmail.com
    on_failure: change
    on_success: never