language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.1.3
  - 2.1.4

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - thucquyendn@gmail.com
    on_failure: change
    on_success: never